// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75use-_osDY2kSTpyBL9bkesWt8__Up0',
    appId: '1:330142015513:web:9cf471a55d5f6caebeca88',
    messagingSenderId: '330142015513',
    projectId: 'shopping-app-6275f',
    authDomain: 'shopping-app-6275f.firebaseapp.com',
    storageBucket: 'shopping-app-6275f.appspot.com',
    measurementId: 'G-H1LMPL8B49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAl0F_M41ZTLKnWuDT4zKXlMbGe3EONQ',
    appId: '1:330142015513:android:a3a31b2e16e17ba8beca88',
    messagingSenderId: '330142015513',
    projectId: 'shopping-app-6275f',
    storageBucket: 'shopping-app-6275f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClErrI6qLOCFPTzvEanivc-3lTs5uIVBI',
    appId: '1:330142015513:ios:c5e10c68d30d7d88beca88',
    messagingSenderId: '330142015513',
    projectId: 'shopping-app-6275f',
    storageBucket: 'shopping-app-6275f.appspot.com',
    iosClientId: '330142015513-2mlmllgod5u2acn0eue6r0q0l5571tt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClErrI6qLOCFPTzvEanivc-3lTs5uIVBI',
    appId: '1:330142015513:ios:c5e10c68d30d7d88beca88',
    messagingSenderId: '330142015513',
    projectId: 'shopping-app-6275f',
    storageBucket: 'shopping-app-6275f.appspot.com',
    iosClientId: '330142015513-2mlmllgod5u2acn0eue6r0q0l5571tt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
