// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_P16eNg36uR-w8ZK516Kjf0BARjrxfw',
    appId: '1:625532914770:web:700f5f2c5ba62171e8638b',
    messagingSenderId: '625532914770',
    projectId: 'bkfet-cf67d',
    authDomain: 'bkfet-cf67d.firebaseapp.com',
    storageBucket: 'bkfet-cf67d.appspot.com',
    measurementId: 'G-9SY4HB8LSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmlW3vdzHBVz0GY6qQlQWTAGiHsA45Q4',
    appId: '1:625532914770:android:f5dc2576a219027be8638b',
    messagingSenderId: '625532914770',
    projectId: 'bkfet-cf67d',
    storageBucket: 'bkfet-cf67d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB526Muzq9GSEbYuvoWEmY3iH3AcAxkmEc',
    appId: '1:625532914770:ios:d17a0612874318e1e8638b',
    messagingSenderId: '625532914770',
    projectId: 'bkfet-cf67d',
    storageBucket: 'bkfet-cf67d.appspot.com',
    iosClientId: '625532914770-se76tme1v0nt7hkprm7q8tgsqpptv46d.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB526Muzq9GSEbYuvoWEmY3iH3AcAxkmEc',
    appId: '1:625532914770:ios:d17a0612874318e1e8638b',
    messagingSenderId: '625532914770',
    projectId: 'bkfet-cf67d',
    storageBucket: 'bkfet-cf67d.appspot.com',
    iosClientId: '625532914770-se76tme1v0nt7hkprm7q8tgsqpptv46d.apps.googleusercontent.com',
    iosBundleId: 'com.example.app2',
  );
}
